# Generated by Django 4.2.16 on 2024-12-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlImagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtidas', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('comentarios', models.ManyToManyField(related_name='postagens_comentario', to='raizes_da_arte.comentario')),
                ('imagens', models.ManyToManyField(related_name='postagens_imagem', to='raizes_da_arte.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=500)),
                ('cep', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('imagem_perfil', models.FilePathField(path='/img')),
                ('postagens', models.ManyToManyField(related_name='usuario_postagem', to='raizes_da_arte.postagem')),
            ],
        ),
        migrations.AddField(
            model_name='postagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagem_usuario', to='raizes_da_arte.user'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_postagem', to='raizes_da_arte.postagem'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_postagem', to='raizes_da_arte.postagem'),
        ),
    ]
